module USER_ROLES
  SUPER_ADMIN = "SUPER_ADMIN"
  ADMIN = "ADMIN"
  MODERATOR = "MODERATOR"
  REGULAR = "REGULAR"

  ALL_ROLES = [ SUPER_ADMIN, ADMIN, MODERATOR, REGULAR ].freeze
end

module USER_THEMES
  LIGHT = "light"
  DARK = "dark"

  ALL_THEMES = [ LIGHT, DARK ].freeze
end

module USER_LOCALES
  ENGLISH = "en"
  RUSSIAN = "ru"

  ALL_LOCALES = [ ENGLISH, RUSSIAN ].freeze
end

module LINK_TYPES
  TRAILER = "TRAILER"
  LONGPLAY = "LONGPLAY"
  SPEEDRUN = "SPEEDRUN"
  OTHER = "OTHER"

  ALL_TYPES = [ TRAILER, LONGPLAY, SPEEDRUN, OTHER ].freeze
end

module ASSET_TYPES
  COVER = "COVER"
  SCREENSHOT = "SCREENSHOT"
  MANUAL = "MANUAL"

  ALL_TYPES = [ COVER, SCREENSHOT, MANUAL ].freeze
end
